using Microsoft.CodeAnalysis;
using System.Xml.Serialization;
using System.IO;
using System;
using SmartVault.Library;
using System.Diagnostics;

namespace SmartVault.CodeGeneration
{
    [Generator]
    public class BusinessObjectSourceGenerator : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {
            // Find the main method
            IMethodSymbol? mainMethod = context.Compilation.GetEntryPoint(context.CancellationToken);

            // Build up the source code
            foreach (AdditionalText file in context.AdditionalFiles)
            {
                string fileContents = file.GetText().ToString();

                XmlSerializer serializer = new(typeof(BusinessObject));
                using StringReader reader = new(fileContents);
                string name = Path.GetFileNameWithoutExtension(file.Path);
                BusinessObject businessObjectModel = (BusinessObject)serializer.Deserialize(reader);

                string propertiesString = "";
                for (int j = 0; j < businessObjectModel.PropertyGroup.Property.Count; j++)
                {
                    Property property = businessObjectModel.PropertyGroup.Property[j];
                    propertiesString += string.Format("        public {0} {1} {{ get; set; }}{2}", property.Type, property.Name, Environment.NewLine);
                }

                string businessObjectClassString = $@"// <auto-generated/>
namespace {mainMethod.ContainingNamespace.ToDisplayString()}.BusinessObjects
{{
    public partial class {name}
    {{
        {propertiesString}
    }}
}}
";
                context.AddSource($"{name}.generated.cs", businessObjectClassString);
            }
        }

        public void Initialize(GeneratorInitializationContext context)
        {
            // No initialization required for this one
        }
    }
}